#To send the responses
###To create the warden
post http://localhost:4700/warden-api/register
Content-Type: application/json

{
    "role":"warden",
    "firstName": "Abhishek2",
    "email":"abhi1234@gmail.com",
    "password":"abhi1234",
     "phone":9234567234
}

###To sign in as warden
post http://localhost:4700/warden-api/login
Content-Type: application/json

{
    "email":"abhi1234@gmail.com",
    "password":"abhi1234"
}

###To verify the complaint by the warden
put http://localhost:4700/warden-api/warden/verify
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODVlZmIyMDkyYWFiMmY1MzE5OTQ0N2UiLCJlbWFpbCI6ImFiaGkxMjM0QGdtYWlsLmNvbSIsInJvbGUiOiJ3YXJkZW4iLCJpYXQiOjE3NTEwNTUxNDIsImV4cCI6MTc1MTE0MTU0Mn0.ww465sX4B9lg0DCnio20R879NGGYqk-1rrGY0y5B83E

{
  "complaintId": "685ef8ba92aab2f531994470",
  "isLegit": true,
  "remarks": "Water leakage confirmed in Room 102"
}

###To send the notifications to the hostellers
post http://localhost:4700/warden-api/warden/notify
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODVlZmIyMDkyYWFiMmY1MzE5OTQ0N2UiLCJlbWFpbCI6ImFiaGkxMjM0QGdtYWlsLmNvbSIsInJvbGUiOiJ3YXJkZW4iLCJpYXQiOjE3NTEwNTUxNDIsImV4cCI6MTc1MTE0MTU0Mn0.ww465sX4B9lg0DCnio20R879NGGYqk-1rrGY0y5B83E

{
  "complaintId": "685ef8ba92aab2f531994470",
  "title":"Your Complaint is verified",
  "description":"Your room isn't cleaned since for 4 weeks, it will be completed within 2 working days."
}


###get the complaints
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2ODVkODI3NTk5ZWQzNGI0NThiNmFjOWMiLCJlbWFpbCI6ImFiaGkxMjM0QGdtYWlsLmNvbSIsInJvbGUiOiJ3YXJkZW4iLCJpYXQiOjE3NTA5NjE3OTQsImV4cCI6MTc1MTA0ODE5NH0.OMARqeXv9HuLCE0d77WHsIgfr10X8vUtBIjGyRgfsPs
